# Generated by Django 5.2.10 on 2026-02-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0004_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comportamiento', models.CharField(max_length=50)),
                ('severidad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo')], default='Pendiente', max_length=10)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.ubicacion')),
            ],
        ),
    ]
