# Generated by Django 5.2.10 on 2026-02-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0005_alertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
